{% set version = "0.17.1" %}

package:
  name: prometheus_client
  version: {{ version }}

source:
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: efd821d1d73e1d45d4ad46c9bef38a1cc646769346db0e70c520a7ec9409e3a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  summary: Python client for the Prometheus monitoring system
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
