{% set version = "0.14.1" %}

package:
  name: prometheus_client
  version: {{ version }}

source:
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: db2b212c690fb1dbd0da807753af9247da28610c1d93fa12fa0b43bd30d22964

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  summary: Python client for the Prometheus monitoring system
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
